[package]
name = "virtual-gamepad-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.94"
clap = { version = "4.5.23", features = ["derive", "string"] }
env_logger = "0.11.5"
evdev = "0.13.0"
log = "0.4"
